### ISSUE TITLE
MetaMask Max Token String

### ISSUE THREAD

**Issue by Karotoka** [kalidao/kali-contracts#1]
Didn't know this but I set up a Test DAO with token - bigupyourself - https://rinkeby.etherscan.io/token/0x9dd998bb51b2971fefd1724029883ea5ff99c63d

When I try to import token to MM, I get an error stating 'Symbol must be 11 characters or fewer'. Perhaps we should limit the Token Name field on UI to 11 characters to make sure DAOs can actually import tokens into MM.

**Comment by nerderlyne** [comment]
I did not know this either! Will make the nit :)

**Comment by nerderlyne** [comment]
There is a kali-ui repo that you can use for UI-related issues

**Comment by Karotoka** [comment]
Yah, sorry Shiv. Initially though we should fix this in the uint/string input but it probably makes more sense to put in in the UI itself.
