### ISSUE TITLE
ShareManager suggestions

### ISSUE THREAD

**Issue by audsssy** [kalidao/kali-contracts#13]
Maybe the two main requirements from smart contract perspective are to limit the manager grant to a certain ceiling of tokens and an expiration deadline for the minting powers. Maybe similar parameters for burning.

by Ivelin

**Comment by ivelin** [comment]
Here is some more context to what we are trying to do:
https://github.com/SporosDAO/sweat-token/pull/57#discussion_r888400024

**Comment by ivelin** [comment]
We can close this issue.

`ProjectManager` contract is now available as a Kali extension and via SporosDAO UI app. 
[Blog post](https://medium.com/sporos-dao/how-to-write-and-test-a-kalidao-extension-aa686193120a)
